### Create a new product
POST http://localhost:5025/pay
Content-Type: application/json

{
    "Pan": "1111111111111111",
    "Amount": 3000000,
    "Cvv": "1234",
    "Name": "Henry Ford",
    "Expiry": "0124"
}